module FIXConstants

export # Message Types
    MSG_HEARTBEAT, MSG_TEST_REQUEST, MSG_REJECT, MSG_LOGOUT,
    MSG_EXECUTION_REPORT, MSG_ORDER_CANCEL_REJECT, MSG_LOGON, MSG_NEWS,
    MSG_NEW_ORDER_SINGLE, MSG_NEW_ORDER_LIST, MSG_ORDER_CANCEL_REQUEST,
    MSG_LIST_STATUS, MSG_ORDER_MASS_CANCEL_REQUEST, MSG_ORDER_MASS_CANCEL_REPORT,
    MSG_MARKET_DATA_REQUEST, MSG_MARKET_DATA_SNAPSHOT, MSG_MARKET_DATA_INCREMENTAL,
    MSG_MARKET_DATA_REQUEST_REJECT, MSG_INSTRUMENT_LIST_REQUEST, MSG_INSTRUMENT_LIST,
    MSG_ORDER_AMEND_KEEP_PRIORITY, MSG_ORDER_AMEND_REJECT,
    MSG_ORDER_CANCEL_AND_NEW, MSG_LIMIT_QUERY, MSG_LIMIT_RESPONSE

export # Field Tags - Standard
    TAG_BEGIN_STRING, TAG_BODY_LENGTH, TAG_CHECKSUM, TAG_CL_ORD_ID,
    TAG_CUM_QTY, TAG_EXEC_ID, TAG_EXEC_INST, TAG_CURRENCY, TAG_LAST_PX, TAG_LAST_QTY,
    TAG_MSG_SEQ_NUM, TAG_MSG_TYPE, TAG_ORDER_ID, TAG_ORDER_QTY,
    TAG_ORD_STATUS, TAG_ORD_TYPE, TAG_ORIG_CL_ORD_ID, TAG_PRICE,
    TAG_REF_SEQ_NUM, TAG_SENDER_COMP_ID, TAG_SENDING_TIME, TAG_SIDE,
    TAG_SYMBOL, TAG_TARGET_COMP_ID, TAG_TEXT, TAG_TIME_IN_FORCE,
    TAG_TRANSACT_TIME, TAG_URGENCY, TAG_LIST_ID, TAG_NO_ORDERS, TAG_RAW_DATA_LENGTH,
    TAG_RAW_DATA, TAG_ENCRYPT_METHOD, TAG_ORD_REJ_REASON, TAG_HEARTBT_INT,
    TAG_MAX_FLOOR, TAG_TEST_REQ_ID, TAG_RESET_SEQ_NUM_FLAG, TAG_HEADLINE,
    TAG_EXEC_TYPE, TAG_LEAVES_QTY, TAG_CASH_ORDER_QTY, TAG_REF_TAG_ID, TAG_REF_MSG_TYPE,
    TAG_SESSION_REJECT_REASON, TAG_LIST_STATUS_TYPE, TAG_LIST_ORDER_STATUS,
    TAG_CXL_REJ_RESPONSE_TO, TAG_MASS_CANCEL_REQUEST_TYPE,
    TAG_MASS_CANCEL_RESPONSE, TAG_MASS_CANCEL_REJECT_REASON,
    TAG_TOTAL_AFFECTED_ORDERS, TAG_USERNAME, TAG_CONTINGENCY_TYPE,
    TAG_LIST_REJECT_REASON, TAG_ALLOC_ID, TAG_MATCH_TYPE, TAG_TRADE_ID,
    TAG_AGGRESSOR_INDICATOR, TAG_PEG_OFFSET_VALUE, TAG_PEG_MOVE_TYPE,
    TAG_PEG_OFFSET_TYPE, TAG_PEGGED_PRICE, TAG_TARGET_STRATEGY,
    TAG_PEG_PRICE_TYPE, TAG_TRIGGER_TYPE, TAG_TRIGGER_ACTION,
    TAG_TRIGGER_PRICE, TAG_TRIGGER_PRICE_TYPE, TAG_TRIGGER_PRICE_DIRECTION,
    TAG_NO_MISC_FEES, TAG_MISC_FEE_AMT, TAG_MISC_FEE_CURR, TAG_MISC_FEE_TYPE,
    TAG_WORKING_INDICATOR

export # Field Tags - Market Data
    TAG_NO_RELATED_SYM, TAG_MD_REQ_ID, TAG_SUBSCRIPTION_REQUEST_TYPE,
    TAG_MARKET_DEPTH, TAG_AGGREGATED_BOOK, TAG_NO_MD_ENTRY_TYPES,
    TAG_NO_MD_ENTRIES, TAG_MD_ENTRY_TYPE, TAG_MD_ENTRY_PX, TAG_MD_ENTRY_SIZE,
    TAG_MD_UPDATE_ACTION, TAG_MD_REQ_REJ_REASON, TAG_INSTRUMENT_REQ_ID,
    TAG_INSTRUMENT_LIST_REQUEST_TYPE, TAG_MIN_TRADE_VOL, TAG_LAST_FRAGMENT,
    TAG_MIN_PRICE_INCREMENT, TAG_MAX_TRADE_VOL, TAG_AGGRESSOR_SIDE,
    TAG_START_PRICE_RANGE, TAG_END_PRICE_RANGE,
    TAG_MIN_QTY_INCREMENT, TAG_MARKET_MIN_TRADE_VOL, TAG_MARKET_MAX_TRADE_VOL,
    TAG_MARKET_MIN_QTY_INCREMENT, TAG_FIRST_BOOK_UPDATE_ID, TAG_LAST_BOOK_UPDATE_ID

export # Binance Custom Tags
    TAG_REQ_ID, TAG_STRATEGY_ID, TAG_DROP_COPY_FLAG, TAG_RECV_WINDOW,
    TAG_SELF_TRADE_PREVENTION, TAG_CANCEL_RESTRICTIONS,
    TAG_NO_LIMIT_INDICATORS, TAG_LIMIT_TYPE, TAG_LIMIT_COUNT,
    TAG_LIMIT_MAX, TAG_LIMIT_RESET_INTERVAL, TAG_LIMIT_RESET_INTERVAL_RESOLUTION,
    TAG_TRIGGER_TRAILING_DELTA_BIPS, TAG_NO_LIST_TRIGGERING_INSTRUCTIONS,
    TAG_LIST_TRIGGER_TYPE, TAG_LIST_TRIGGER_TRIGGER_INDEX, TAG_LIST_TRIGGER_ACTION,
    TAG_CL_LIST_ID, TAG_ORIG_CL_LIST_ID, TAG_ERROR_CODE, TAG_CUM_QUOTE_QTY,
    TAG_ORDER_CREATION_TIME, TAG_WORKING_FLOOR, TAG_TRAILING_TIME,
    TAG_WORKING_TIME, TAG_PREVENTED_MATCH_ID, TAG_PREVENTED_EXECUTION_PRICE,
    TAG_PREVENTED_EXECUTION_QTY, TAG_TRADE_GROUP_ID, TAG_COUNTER_SYMBOL,
    TAG_COUNTER_ORDER_ID, TAG_PREVENTED_QTY, TAG_LAST_PREVENTED_QTY,
    TAG_SOR, TAG_ORDER_CANCEL_AND_NEW_MODE, TAG_CANCEL_CL_ORD_ID,
    TAG_SECONDARY_SYMBOL, TAG_SECURITY_DESC,
    TAG_MESSAGE_HANDLING, TAG_RESPONSE_MODE, TAG_UUID,
    TAG_ORDER_RATE_LIMIT_EXCEEDED_MODE, TAG_OPO,
    TAG_SBE_SCHEMA_ID, TAG_SBE_SCHEMA_VERSION

export # FIX SBE Constants
    SBE_SCHEMA_ID_FIX, SBE_SCHEMA_VERSION_FIX, SBE_ENCODING_TYPE_LE,
    SBE_SOFH_SIZE, SBE_MESSAGE_HEADER_SIZE,
    SBE_INT8_NULL, SBE_INT16_NULL, SBE_INT32_NULL, SBE_INT64_NULL,
    SBE_UINT8_NULL, SBE_UINT16_NULL, SBE_UINT32_NULL, SBE_UINT64_NULL

export # FIX SBE Template IDs - Admin
    SBE_TEMPLATE_LOGON, SBE_TEMPLATE_LOGON_ACK, SBE_TEMPLATE_LOGOUT,
    SBE_TEMPLATE_HEARTBEAT, SBE_TEMPLATE_TEST_REQUEST,
    SBE_TEMPLATE_REJECT, SBE_TEMPLATE_NEWS

export # FIX SBE Template IDs - Order Entry
    SBE_TEMPLATE_NEW_ORDER_SINGLE, SBE_TEMPLATE_EXECUTION_REPORT,
    SBE_TEMPLATE_EXECUTION_REPORT_ACK, SBE_TEMPLATE_ORDER_CANCEL_REQUEST,
    SBE_TEMPLATE_ORDER_CANCEL_REJECT, SBE_TEMPLATE_ORDER_MASS_CANCEL_REQUEST,
    SBE_TEMPLATE_ORDER_MASS_CANCEL_REPORT, SBE_TEMPLATE_NEW_ORDER_LIST,
    SBE_TEMPLATE_LIST_STATUS, SBE_TEMPLATE_ORDER_AMEND_KEEP_PRIORITY,
    SBE_TEMPLATE_ORDER_AMEND_REJECT, SBE_TEMPLATE_ORDER_CANCEL_REQUEST_AND_NEW,
    SBE_TEMPLATE_LIMIT_QUERY, SBE_TEMPLATE_LIMIT_RESPONSE

export # FIX SBE Template IDs - Market Data
    SBE_TEMPLATE_MARKET_DATA_REQUEST, SBE_TEMPLATE_MARKET_DATA_REQUEST_REJECT,
    SBE_TEMPLATE_MARKET_DATA_SNAPSHOT, SBE_TEMPLATE_MARKET_DATA_INCREMENTAL_TRADE,
    SBE_TEMPLATE_MARKET_DATA_INCREMENTAL_BOOK_TICKER,
    SBE_TEMPLATE_MARKET_DATA_INCREMENTAL_DEPTH,
    SBE_TEMPLATE_INSTRUMENT_LIST_REQUEST, SBE_TEMPLATE_INSTRUMENT_LIST

export # Side Values
    SIDE_BUY, SIDE_SELL

export # Order Type Values
    ORD_TYPE_MARKET, ORD_TYPE_LIMIT, ORD_TYPE_STOP, ORD_TYPE_STOP_LIMIT, ORD_TYPE_PEGGED

export # Time In Force Values
    TIF_GTC, TIF_IOC, TIF_FOK

export # Exec Type Values
    EXEC_TYPE_NEW, EXEC_TYPE_CANCELED, EXEC_TYPE_REPLACED,
    EXEC_TYPE_REJECTED, EXEC_TYPE_TRADE, EXEC_TYPE_EXPIRED

export # Order Status Values
    ORD_STATUS_NEW, ORD_STATUS_PARTIALLY_FILLED, ORD_STATUS_FILLED,
    ORD_STATUS_CANCELED, ORD_STATUS_PENDING_CANCEL, ORD_STATUS_REJECTED,
    ORD_STATUS_PENDING_NEW, ORD_STATUS_EXPIRED

export # Contingency Type Values
    CONTINGENCY_OCO, CONTINGENCY_OTO

export # Self Trade Prevention Values
    STP_NONE, STP_EXPIRE_TAKER, STP_EXPIRE_MAKER, STP_EXPIRE_BOTH, STP_DECREMENT, STP_TRANSFER

export # Mass Cancel Values
    MASS_CANCEL_SYMBOL

export # Cancel Reject Response To Values
    CXL_REJ_ORDER_CANCEL_REQUEST

export # List Status Values
    LIST_STATUS_RESPONSE, LIST_STATUS_EXEC_STARTED, LIST_STATUS_ALL_DONE, LIST_STATUS_UPDATED

export # List Order Status Values
    LIST_ORDER_STATUS_EXECUTING, LIST_ORDER_STATUS_ALL_DONE, LIST_ORDER_STATUS_REJECT

export # List Reject Reason Values
    LIST_REJECT_REASON_OTHER

export # Limit Type Values (Order Entry)
    LIMIT_TYPE_ORDER, LIMIT_TYPE_MESSAGE

export # Limit Type Values (Market Data)
    LIMIT_TYPE_MD_MESSAGE, LIMIT_TYPE_MD_SUBSCRIPTION

export # Market Data Entry Types
    MD_ENTRY_BID, MD_ENTRY_OFFER, MD_ENTRY_TRADE

export # Market Data Update Actions
    MD_UPDATE_NEW, MD_UPDATE_CHANGE, MD_UPDATE_DELETE

export # Market Data Subscription Types
    MD_SUBSCRIBE, MD_UNSUBSCRIBE

export # Instrument List Request Types
    INSTRUMENT_LIST_SINGLE, INSTRUMENT_LIST_ALL

export # Trigger Direction Values
    TRIGGER_UP, TRIGGER_DOWN

export # ExecInst Values
    EXEC_INST_PARTICIPATE_DONT_INITIATE

export # Peg Order Values
    PEG_PRICE_MARKET, PEG_PRICE_PRIMARY,
    PEG_MOVE_FIXED, PEG_OFFSET_PRICE_TIER

export # Trigger Values (for stop/trailing orders)
    TRIGGER_TYPE_PRICE_MOVEMENT, TRIGGER_ACTION_ACTIVATE,
    TRIGGER_PRICE_TYPE_LAST_TRADE

export # Message Handling Values
    MSG_HANDLING_UNORDERED, MSG_HANDLING_SEQUENTIAL

export # Response Mode Values
    RESPONSE_MODE_EVERYTHING, RESPONSE_MODE_ONLY_ACKS

export # Cancel and New Order Mode Values
    XCN_MODE_STOP_ON_FAILURE, XCN_MODE_ALLOW_FAILURE

export # Order Rate Limit Exceeded Mode Values
    RATE_LIMIT_MODE_DO_NOTHING, RATE_LIMIT_MODE_CANCEL_ONLY

export # Cancel Restrictions Values
    CANCEL_ONLY_NEW, CANCEL_ONLY_PARTIALLY_FILLED

export # List Triggering Instruction Values
    LIST_TRIGGER_ACTIVATED, LIST_TRIGGER_PARTIALLY_FILLED, LIST_TRIGGER_FILLED,
    LIST_TRIGGER_ACTION_RELEASE, LIST_TRIGGER_ACTION_CANCEL

export # Session Reject Reason Values
    REJECT_INVALID_TAG_NUMBER, REJECT_REQUIRED_TAG_MISSING,
    REJECT_TAG_NOT_DEFINED_FOR_MESSAGE, REJECT_UNDEFINED_TAG,
    REJECT_VALUE_INCORRECT, REJECT_INCORRECT_DATA_FORMAT,
    REJECT_SIGNATURE_PROBLEM, REJECT_SENDINGTIME_ACCURACY,
    REJECT_XML_VALIDATION_ERROR, REJECT_TAG_APPEARS_MORE_THAN_ONCE,
    REJECT_TAG_OUT_OF_ORDER, REJECT_REPEATING_GROUP_OUT_OF_ORDER,
    REJECT_INCORRECT_NUMINGROUP, REJECT_OTHER

# =============================================================================
# FIX Message Types (MsgType tag 35)
# =============================================================================

# Admin Messages
const MSG_HEARTBEAT = "0"
const MSG_TEST_REQUEST = "1"
const MSG_REJECT = "3"
const MSG_LOGOUT = "5"
const MSG_LOGON = "A"
const MSG_NEWS = "B"

# Order Entry Application Messages
const MSG_EXECUTION_REPORT = "8"
const MSG_ORDER_CANCEL_REJECT = "9"
const MSG_NEW_ORDER_SINGLE = "D"
const MSG_NEW_ORDER_LIST = "E"
const MSG_ORDER_CANCEL_REQUEST = "F"
const MSG_LIST_STATUS = "N"
const MSG_ORDER_MASS_CANCEL_REQUEST = "q"
const MSG_ORDER_MASS_CANCEL_REPORT = "r"

# Market Data Messages
const MSG_MARKET_DATA_REQUEST = "V"
const MSG_MARKET_DATA_SNAPSHOT = "W"
const MSG_MARKET_DATA_INCREMENTAL = "X"
const MSG_MARKET_DATA_REQUEST_REJECT = "Y"
const MSG_INSTRUMENT_LIST_REQUEST = "x"
const MSG_INSTRUMENT_LIST = "y"

# Binance Custom Messages
const MSG_ORDER_AMEND_KEEP_PRIORITY = "XAK"
const MSG_ORDER_AMEND_REJECT = "XAR"
const MSG_ORDER_CANCEL_AND_NEW = "XCN"
const MSG_LIMIT_QUERY = "XLQ"
const MSG_LIMIT_RESPONSE = "XLR"

# =============================================================================
# Standard FIX Field Tags
# =============================================================================

const TAG_BEGIN_STRING = 8
const TAG_BODY_LENGTH = 9
const TAG_CHECKSUM = 10
const TAG_CL_ORD_ID = 11
const TAG_CUM_QTY = 14
const TAG_CURRENCY = 15
const TAG_EXEC_ID = 17
const TAG_EXEC_INST = 18
const TAG_LAST_PX = 31
const TAG_LAST_QTY = 32
const TAG_MSG_SEQ_NUM = 34
const TAG_MSG_TYPE = 35
const TAG_ORDER_ID = 37
const TAG_ORDER_QTY = 38
const TAG_ORD_STATUS = 39
const TAG_ORD_TYPE = 40
const TAG_ORIG_CL_ORD_ID = 41
const TAG_PRICE = 44
const TAG_REF_SEQ_NUM = 45
const TAG_SENDER_COMP_ID = 49
const TAG_SENDING_TIME = 52
const TAG_SIDE = 54
const TAG_SYMBOL = 55
const TAG_TARGET_COMP_ID = 56
const TAG_TEXT = 58
const TAG_TIME_IN_FORCE = 59
const TAG_TRANSACT_TIME = 60
const TAG_URGENCY = 61
const TAG_LIST_ID = 66
const TAG_ALLOC_ID = 70
const TAG_NO_ORDERS = 73
const TAG_RAW_DATA_LENGTH = 95
const TAG_RAW_DATA = 96
const TAG_ENCRYPT_METHOD = 98
const TAG_ORD_REJ_REASON = 103
const TAG_HEARTBT_INT = 108
const TAG_MAX_FLOOR = 111
const TAG_TEST_REQ_ID = 112
const TAG_RESET_SEQ_NUM_FLAG = 141
const TAG_HEADLINE = 148
const TAG_NO_RELATED_SYM = 146
const TAG_EXEC_TYPE = 150
const TAG_LEAVES_QTY = 151
const TAG_CASH_ORDER_QTY = 152
const TAG_PEG_OFFSET_VALUE = 211
const TAG_MD_REQ_ID = 262
const TAG_SUBSCRIPTION_REQUEST_TYPE = 263
const TAG_MARKET_DEPTH = 264
const TAG_AGGREGATED_BOOK = 266
const TAG_NO_MD_ENTRY_TYPES = 267
const TAG_NO_MD_ENTRIES = 268
const TAG_MD_ENTRY_TYPE = 269
const TAG_MD_ENTRY_PX = 270
const TAG_MD_ENTRY_SIZE = 271
const TAG_MD_UPDATE_ACTION = 279
const TAG_MD_REQ_REJ_REASON = 281
const TAG_INSTRUMENT_REQ_ID = 320
const TAG_REF_TAG_ID = 371
const TAG_REF_MSG_TYPE = 372
const TAG_SESSION_REJECT_REASON = 373
const TAG_LIST_STATUS_TYPE = 429
const TAG_LIST_ORDER_STATUS = 431
const TAG_CXL_REJ_RESPONSE_TO = 434
const TAG_MASS_CANCEL_REQUEST_TYPE = 530
const TAG_MASS_CANCEL_RESPONSE = 531
const TAG_MASS_CANCEL_REJECT_REASON = 532
const TAG_TOTAL_AFFECTED_ORDERS = 533
const TAG_USERNAME = 553
const TAG_INSTRUMENT_LIST_REQUEST_TYPE = 559
const TAG_MIN_TRADE_VOL = 562
const TAG_MATCH_TYPE = 574
const TAG_NO_MISC_FEES = 136
const TAG_MISC_FEE_AMT = 137
const TAG_MISC_FEE_CURR = 138
const TAG_MISC_FEE_TYPE = 139
const TAG_WORKING_INDICATOR = 636
const TAG_PEG_MOVE_TYPE = 835
const TAG_PEG_OFFSET_TYPE = 836
const TAG_PEGGED_PRICE = 839
const TAG_TARGET_STRATEGY = 847
const TAG_LAST_FRAGMENT = 893
const TAG_MIN_PRICE_INCREMENT = 969
const TAG_TRADE_ID = 1003
const TAG_AGGRESSOR_INDICATOR = 1057
const TAG_PEG_PRICE_TYPE = 1094
const TAG_TRIGGER_TYPE = 1100
const TAG_TRIGGER_ACTION = 1101
const TAG_TRIGGER_PRICE = 1102
const TAG_TRIGGER_PRICE_TYPE = 1107
const TAG_TRIGGER_PRICE_DIRECTION = 1109
const TAG_MAX_TRADE_VOL = 1140
const TAG_CONTINGENCY_TYPE = 1385
const TAG_LIST_REJECT_REASON = 1386
const TAG_AGGRESSOR_SIDE = 2446
const TAG_START_PRICE_RANGE = 2551
const TAG_END_PRICE_RANGE = 2552

# =============================================================================
# Binance Custom Field Tags
# =============================================================================

const TAG_REQ_ID = 6136
const TAG_STRATEGY_ID = 7940
const TAG_DROP_COPY_FLAG = 9406
const TAG_RECV_WINDOW = 25000
const TAG_SELF_TRADE_PREVENTION = 25001
const TAG_CANCEL_RESTRICTIONS = 25002
const TAG_NO_LIMIT_INDICATORS = 25003
const TAG_LIMIT_TYPE = 25004
const TAG_LIMIT_COUNT = 25005
const TAG_LIMIT_MAX = 25006
const TAG_LIMIT_RESET_INTERVAL = 25007
const TAG_LIMIT_RESET_INTERVAL_RESOLUTION = 25008
const TAG_TRIGGER_TRAILING_DELTA_BIPS = 25009
const TAG_NO_LIST_TRIGGERING_INSTRUCTIONS = 25010
const TAG_LIST_TRIGGER_TYPE = 25011
const TAG_LIST_TRIGGER_TRIGGER_INDEX = 25012
const TAG_LIST_TRIGGER_ACTION = 25013
const TAG_CL_LIST_ID = 25014
const TAG_ORIG_CL_LIST_ID = 25015
const TAG_ERROR_CODE = 25016
const TAG_CUM_QUOTE_QTY = 25017
const TAG_ORDER_CREATION_TIME = 25018
const TAG_WORKING_FLOOR = 25021
const TAG_TRAILING_TIME = 25022
const TAG_WORKING_TIME = 25023
const TAG_PREVENTED_MATCH_ID = 25024
const TAG_PREVENTED_EXECUTION_PRICE = 25025
const TAG_PREVENTED_EXECUTION_QTY = 25026
const TAG_TRADE_GROUP_ID = 25027
const TAG_COUNTER_SYMBOL = 25028
const TAG_COUNTER_ORDER_ID = 25029
const TAG_PREVENTED_QTY = 25030
const TAG_LAST_PREVENTED_QTY = 25031
const TAG_SOR = 25032
const TAG_ORDER_CANCEL_AND_NEW_MODE = 25033
const TAG_CANCEL_CL_ORD_ID = 25034
const TAG_SECONDARY_SYMBOL = 25019
const TAG_SECURITY_DESC = 107
const TAG_MESSAGE_HANDLING = 25035
const TAG_RESPONSE_MODE = 25036
const TAG_UUID = 25037
const TAG_ORDER_RATE_LIMIT_EXCEEDED_MODE = 25038
const TAG_MIN_QTY_INCREMENT = 25039
const TAG_MARKET_MIN_TRADE_VOL = 25040
const TAG_MARKET_MAX_TRADE_VOL = 25041
const TAG_MARKET_MIN_QTY_INCREMENT = 25042
const TAG_FIRST_BOOK_UPDATE_ID = 25043
const TAG_LAST_BOOK_UPDATE_ID = 25044
const TAG_OPO = 25046                        # One Party Only flag for order lists
const TAG_SBE_SCHEMA_ID = 25050              # SBE Schema ID for Logon
const TAG_SBE_SCHEMA_VERSION = 25051         # SBE Schema Version for Logon

# =============================================================================
# Field Value Enums
# =============================================================================

# Side (54)
const SIDE_BUY = "1"
const SIDE_SELL = "2"

# OrdType (40)
const ORD_TYPE_MARKET = "1"
const ORD_TYPE_LIMIT = "2"
const ORD_TYPE_STOP = "3"
const ORD_TYPE_STOP_LIMIT = "4"
const ORD_TYPE_PEGGED = "P"

# TimeInForce (59)
const TIF_GTC = "1"
const TIF_IOC = "3"
const TIF_FOK = "4"

# ExecType (150)
const EXEC_TYPE_NEW = "0"
const EXEC_TYPE_CANCELED = "4"
const EXEC_TYPE_REPLACED = "5"
const EXEC_TYPE_REJECTED = "8"
const EXEC_TYPE_TRADE = "F"
const EXEC_TYPE_EXPIRED = "C"

# OrdStatus (39)
const ORD_STATUS_NEW = "0"
const ORD_STATUS_PARTIALLY_FILLED = "1"
const ORD_STATUS_FILLED = "2"
const ORD_STATUS_CANCELED = "4"
const ORD_STATUS_PENDING_CANCEL = "6"
const ORD_STATUS_REJECTED = "8"
const ORD_STATUS_PENDING_NEW = "A"
const ORD_STATUS_EXPIRED = "C"

# ContingencyType (1385)
# Note: OTOCO also uses ContingencyType=2 (same as OTO)
# The difference is determined by the number of orders and triggering instructions
const CONTINGENCY_OCO = "1"
const CONTINGENCY_OTO = "2"

# SelfTradePreventionMode (25001)
const STP_NONE = "1"
const STP_EXPIRE_TAKER = "2"
const STP_EXPIRE_MAKER = "3"
const STP_EXPIRE_BOTH = "4"
const STP_DECREMENT = "5"
const STP_TRANSFER = "6"           # Added from schema

# MassCancelRequestType (530)
const MASS_CANCEL_SYMBOL = "1"

# CxlRejResponseTo (434)
const CXL_REJ_ORDER_CANCEL_REQUEST = "1"

# ListStatusType (429)
const LIST_STATUS_RESPONSE = "2"
const LIST_STATUS_EXEC_STARTED = "4"
const LIST_STATUS_ALL_DONE = "5"
const LIST_STATUS_UPDATED = "100"

# ListOrderStatus (431)
const LIST_ORDER_STATUS_EXECUTING = "3"
const LIST_ORDER_STATUS_ALL_DONE = "6"
const LIST_ORDER_STATUS_REJECT = "7"

# ListRejectReason (1386)
const LIST_REJECT_REASON_OTHER = "99"

# LimitType (25004) - Order Entry
const LIMIT_TYPE_ORDER = "1"
const LIMIT_TYPE_MESSAGE = "2"

# LimitType (25004) - Market Data
const LIMIT_TYPE_MD_MESSAGE = "2"
const LIMIT_TYPE_MD_SUBSCRIPTION = "3"

# MDEntryType (269)
const MD_ENTRY_BID = "0"
const MD_ENTRY_OFFER = "1"
const MD_ENTRY_TRADE = "2"

# MDUpdateAction (279)
const MD_UPDATE_NEW = "0"
const MD_UPDATE_CHANGE = "1"
const MD_UPDATE_DELETE = "2"

# SubscriptionRequestType (263)
const MD_SUBSCRIBE = "1"
const MD_UNSUBSCRIBE = "2"

# InstrumentListRequestType (559)
const INSTRUMENT_LIST_SINGLE = "0"
const INSTRUMENT_LIST_ALL = "4"

# TriggerPriceDirection (1109)
const TRIGGER_UP = "U"
const TRIGGER_DOWN = "D"

# ExecInst (18)
const EXEC_INST_PARTICIPATE_DONT_INITIATE = "6"

# PegPriceType (1094)
const PEG_PRICE_MARKET = "4"
const PEG_PRICE_PRIMARY = "5"

# PegMoveType (835)
const PEG_MOVE_FIXED = "1"

# PegOffsetType (836)
const PEG_OFFSET_PRICE_TIER = "3"

# TriggerType (1100)
const TRIGGER_TYPE_PRICE_MOVEMENT = "4"

# TriggerAction (1101)
const TRIGGER_ACTION_ACTIVATE = "1"

# TriggerPriceType (1107)
const TRIGGER_PRICE_TYPE_LAST_TRADE = "2"

# MessageHandling (25035)
const MSG_HANDLING_UNORDERED = "1"
const MSG_HANDLING_SEQUENTIAL = "2"

# ResponseMode (25036)
const RESPONSE_MODE_EVERYTHING = "1"
const RESPONSE_MODE_ONLY_ACKS = "2"

# OrderCancelRequestAndNewOrderSingleMode (25033)
const XCN_MODE_STOP_ON_FAILURE = "1"
const XCN_MODE_ALLOW_FAILURE = "2"

# OrderRateLimitExceededMode (25038)
const RATE_LIMIT_MODE_DO_NOTHING = "1"
const RATE_LIMIT_MODE_CANCEL_ONLY = "2"

# CancelRestrictions (25002)
const CANCEL_ONLY_NEW = "1"
const CANCEL_ONLY_PARTIALLY_FILLED = "2"

# ListTriggerType (25011)
const LIST_TRIGGER_ACTIVATED = "1"
const LIST_TRIGGER_PARTIALLY_FILLED = "2"
const LIST_TRIGGER_FILLED = "3"

# ListTriggerAction (25013)
const LIST_TRIGGER_ACTION_RELEASE = "1"
const LIST_TRIGGER_ACTION_CANCEL = "2"

# SessionRejectReason (373)
const REJECT_INVALID_TAG_NUMBER = "0"
const REJECT_REQUIRED_TAG_MISSING = "1"
const REJECT_TAG_NOT_DEFINED_FOR_MESSAGE = "2"
const REJECT_UNDEFINED_TAG = "3"
const REJECT_VALUE_INCORRECT = "5"
const REJECT_INCORRECT_DATA_FORMAT = "6"
const REJECT_SIGNATURE_PROBLEM = "8"
const REJECT_SENDINGTIME_ACCURACY = "10"
const REJECT_XML_VALIDATION_ERROR = "12"
const REJECT_TAG_APPEARS_MORE_THAN_ONCE = "13"
const REJECT_TAG_OUT_OF_ORDER = "14"
const REJECT_REPEATING_GROUP_OUT_OF_ORDER = "15"
const REJECT_INCORRECT_NUMINGROUP = "16"
const REJECT_OTHER = "99"

# =============================================================================
# FIX SBE Constants (spot-fixsbe-1_0.xml)
# =============================================================================
# Schema ID: 1, Version: 0
# Wire Format: <SOFH (6 bytes)> <message header (16 bytes)> <message (N bytes)>

# Schema Information
const SBE_SCHEMA_ID_FIX = UInt16(1)           # FIX SBE schema ID
const SBE_SCHEMA_VERSION_FIX = UInt16(0)      # FIX SBE schema version
const SBE_ENCODING_TYPE_LE = UInt16(0xEB50)   # Little-endian encoding

# Header Sizes
const SBE_SOFH_SIZE = 6                        # Simple Open Framing Header (messageLength:4 + encodingType:2)
const SBE_MESSAGE_HEADER_SIZE = 20             # FIX SBE message header (blockLength:2 + templateId:2 + schemaId:2 + version:2 + seqNum:4 + sendingTime:8)

# SBE Null Values (for optional fields)
const SBE_INT8_NULL = typemax(Int8)
const SBE_INT16_NULL = typemax(Int16)
const SBE_INT32_NULL = typemax(Int32)
const SBE_INT64_NULL = typemax(Int64)
const SBE_UINT8_NULL = typemax(UInt8)
const SBE_UINT16_NULL = typemax(UInt16)
const SBE_UINT32_NULL = typemax(UInt32)
const SBE_UINT64_NULL = typemax(UInt64)

# FIX SBE Template IDs (from spot-fixsbe-1_0.xml)
# Admin Messages
const SBE_TEMPLATE_HEARTBEAT = UInt16(20001)
const SBE_TEMPLATE_TEST_REQUEST = UInt16(20002)
const SBE_TEMPLATE_REJECT = UInt16(20003)
const SBE_TEMPLATE_LOGOUT = UInt16(20004)
const SBE_TEMPLATE_LOGON = UInt16(20008)
const SBE_TEMPLATE_LOGON_ACK = UInt16(20009)
const SBE_TEMPLATE_NEWS = UInt16(20100)

# Order Entry Messages
const SBE_TEMPLATE_ORDER_CANCEL_REQUEST_AND_NEW = UInt16(97)  # XCN
const SBE_TEMPLATE_EXECUTION_REPORT = UInt16(98)
const SBE_TEMPLATE_NEW_ORDER_SINGLE = UInt16(99)
const SBE_TEMPLATE_NEW_ORDER_LIST = UInt16(100)
const SBE_TEMPLATE_ORDER_CANCEL_REQUEST = UInt16(101)
const SBE_TEMPLATE_LIST_STATUS = UInt16(102)
const SBE_TEMPLATE_ORDER_MASS_CANCEL_REQUEST = UInt16(103)
const SBE_TEMPLATE_ORDER_MASS_CANCEL_REPORT = UInt16(104)
const SBE_TEMPLATE_ORDER_AMEND_KEEP_PRIORITY = UInt16(105)  # XAK
const SBE_TEMPLATE_ORDER_AMEND_REJECT = UInt16(106)          # XAR
const SBE_TEMPLATE_LIMIT_QUERY = UInt16(120)                 # XLQ
const SBE_TEMPLATE_LIMIT_RESPONSE = UInt16(121)              # XLR
const SBE_TEMPLATE_ORDER_CANCEL_REJECT = UInt16(96)
const SBE_TEMPLATE_EXECUTION_REPORT_ACK = UInt16(198)

# Market Data Messages
const SBE_TEMPLATE_INSTRUMENT_LIST_REQUEST = UInt16(200)
const SBE_TEMPLATE_INSTRUMENT_LIST = UInt16(201)
const SBE_TEMPLATE_MARKET_DATA_REQUEST = UInt16(202)
const SBE_TEMPLATE_MARKET_DATA_REQUEST_REJECT = UInt16(203)
const SBE_TEMPLATE_MARKET_DATA_SNAPSHOT = UInt16(204)
const SBE_TEMPLATE_MARKET_DATA_INCREMENTAL_TRADE = UInt16(205)
const SBE_TEMPLATE_MARKET_DATA_INCREMENTAL_BOOK_TICKER = UInt16(206)
const SBE_TEMPLATE_MARKET_DATA_INCREMENTAL_DEPTH = UInt16(207)

end # module
